### ISSUE TITLE
Api call failed

### ISSUE THREAD

**Issue by Naveen-X** [AsmSafone/SafoneAPI#10] opened 2023-06-03 13:54 UTC
Traceback (most recent call last):
  File "/app/Mr.Stark/Stark/__init__.py", line 83, in wrapper
    return await func(client, message, *args, **kwargs)
  File "/app/Mr.Stark/Stark/Plugins/translater.py", line 21, in translate_me
    output = await api.translate(text, target=lang)
  File "/opt/venv/lib/python3.8/site-packages/SafoneAPI/__init__.py", line 913, in translate
    return await self._fetch("translate", text=text, origin=origin, target=target)
  File "/opt/venv/lib/python3.8/site-packages/SafoneAPI/__init__.py", line 68, in _fetch
    raise GenericApiError(
SafoneAPI.GenericApiError: Api Call Failed, Please report this: https://api.safone.me/report

**Comment by AsmSafone** [comment] 2023-07-02 08:49
Can you share reproducible example?

**Comment by filteradmin** [comment] 2023-08-03 21:26
> Traceback (most recent call last): File "/app/Mr.Stark/Stark/**init**.py", line 83, in wrapper return await func(client, message, *args, **kwargs) File "/app/Mr.Stark/Stark/Plugins/translater.py", line 21, in translate_me output = await api.translate(text, target=lang) File "/opt/venv/lib/python3.8/site-packages/SafoneAPI/**init**.py", line 913, in translate return await self._fetch("translate", text=text, origin=origin, target=target) File "/opt/venv/lib/python3.8/site-packages/SafoneAPI/**init**.py", line 68, in _fetch raise GenericApiError( SafoneAPI.GenericApiError: Api Call Failed, Please report this: https://api.safone.me/report

The issue is fixed in [v1.0.42](https://github.com/AsmSafone/SafoneAPI/commit/249dea3a54d16807c9947391bfb308e4ed2645c9)

**Closed** 2023-08-03 21:28 UTC
Labels: bug, documentation
